export const enum TypeActivite {
    DISCUSSION = 'DISCUSSION',
    DEMANDE_OPINION = 'DEMANDE_OPINION',
    TELECONSULTATION = 'TELECONSULTATION',
    DEMANDE_DE_TRANSFERT = 'DEMANDE_DE_TRANSFERT'
}
